name: CI

on:
  push:
    branches: ["main"]

permissions: {} # Each job defines its own permissions explicitly

jobs:
  build:
    name: Build
    permissions:
      contents: write # Access to check out code and install dependencies
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Run benchmarks
        run: |
          pnpm exec vitest bench --run --reporter json --outputFile.json=./test-output.json

      - name: Update README.md
        run: pnpm update-readme

      - name: Format with Oxfmt
        run: pnpm format

      - name: Open or update pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync/benchmark
          delete-branch: true
          commit-message: |
            chore: sync benchmark results
          title: "chore: sync benchmark results"
          body: |
            ## Benchmark results updated

            *Auto-generated by the [ci workflow](.github/workflows/ci.yml).*
          labels: |
            automated
            openapi
